apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.apiPort | default 9000 }}
      targetPort: 9000
      protocol: TCP
      name: api
    - port: {{ .Values.service.consolePort | default 9001 }}
      targetPort: 9001
      protocol: TCP
      name: console
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: {{ .Release.Name }}
